#!/bin/bash
#
# It use the same configuration parameters as Archlinux's package management
# to compile the source code for development.

topdir=`git rev-parse --show-toplevel`
buildsh=$topdir/build.sh

if [ ! -x $buildsh ];then
    pkg=`basename $topdir`
    ncpu=`grep processor /proc/cpuinfo |wc -l`
    repo=`pacman -S -p --print-format '%r' $pkg`
    tempdir=`mktemp -d`

    if [[ $repo = "core" || $repo = "extra" || $repo = "testing" ]]; then
        curl -Ls -o $tempdir/PKGBUILD https://git.archlinux.org/svntogit/packages.git/plain/$pkg/trunk/PKGBUILD
    else
        curl -Ls -o $tempdir/PKGBUILD https://git.archlinux.org/svntogit/community.git/plain/$pkg/trunk/PKGBUILD
    fi

    if [ -f $tempdir/PKGBUILD ];then
        source $tempdir/PKGBUILD

        echo "#!/bin/bash" > $buildsh
        echo "set -x" >> $buildsh
        echo "export LC_ALL=C" >> $buildsh

        echo "pkgname=$pkgname" >> $buildsh
        echo "pkgver=$pkgver" >> $buildsh

        echo 'START=`dirname $(realpath $0)`' >> $buildsh
        echo 'cd $START' >> $buildsh

        echo "if [ ! -f configure ];then" >> $buildsh
        echo "    ./autogen.sh 2>&1 | tee autogen.log" >> $buildsh
        echo "fi" >> $buildsh
        type build| sed 's/^[[:space:]]*//' | sed '1,4d;$d' >> $buildsh
        sed -i \
            -e 's#./configure#./configure --enable-maintainer-mode#' \
            -e '/.\/configure.*;$/s/;/ 2>\&1 | tee configure.log/' \
            -e '/sed.*libtool;$/d' \
            -e 's/make.*/make -j'$(( ncpu+1))' 2>\&1 | tee build.log /' \
            -e '/.\/configure/a cat >> config.h <<EOF\n\n#define debug_print(fmt, ARGS...)  do { fprintf(stderr, "%s:%d:%s(): " fmt "\\n", __FILE__, __LINE__, __FUNCTION__, ##ARGS); } while (0)\nEOF' \
            $buildsh
        chmod +x $buildsh
    fi
    rm -rf $tempdir
fi

if [ -x $buildsh ];then
    $buildsh
fi
